### ISSUE TITLE
Window conflict at gable end

### ISSUE THREAD

**Issue by theoryshaw** [brunopostle/homemaker-addon#11]
Window conflict at gable end

![image](https://user-images.githubusercontent.com/507113/139616783-5556e526-369a-45f8-85f3-ed374c879264.png)

**Comment by brunopostle** [comment]
This is because the add-on currently only looks at the width and height of the wall when fitting windows and doors, not considering that walls can be clipped along the top edge.

Workarounds would be to 1. create a new 'gable' style that only has one window type that requires a wide spacing either side, or 2. split the gable wall up into short segments (that won't get windows) and a longer segment where you want windows to appear:

![image](https://user-images.githubusercontent.com/1747315/139679308-11fd8c6c-78f1-44c8-aa77-b7cd19745ff7.png)

This is still a bug, the add-on shouldn't generate impossible configurations of building components like this.

**Comment by brunopostle** [comment]
After trying all the wrong ways to do this, the right fix is to switch to shorter windows when available in the style, otherwise the window is removed altogether:

![image](https://user-images.githubusercontent.com/1747315/140628960-2116e7e1-e1f4-4b2b-a361-9a2d0082a868.png)
