### ISSUE TITLE
Better handling of non-planar faces in input geometry

### ISSUE THREAD

**Issue by brunopostle** [brunopostle/homemaker-addon#12]
Currently Topologic fails when input geometry is non-planar.

The solution is two parts:

* To identify all non-planar faces in blender, triangulate them and assign an 'error' material to them before handing the geometry off to Topologic/Homemaker.
* Then Homemaker can have a special 'error' style that indicates to the user where their geometry has gone bad.

**Comment by elkmug** [comment]
Would this work for the first bullet point?

```
import bpy
import bmesh

mesh = bpy.context.active_object.data

#you have to be in in edit mode for bmesh & bmesh ops to work
bpy.ops.object.mode_set(mode='EDIT')

md = bmesh.from_edit_mesh(mesh)

output = bmesh.ops.connect_verts_nonplanar(md,angle_limit = 0.001,faces = md.faces)
#https://docs.blender.org/api/master/bmesh.ops.html
#angle_limit is radians

faces = output["faces"]

if len(faces) > 0:

    bpy.ops.mesh.select_all(action='DESELECT')

    new_slot = bpy.ops.object.material_slot_add()

    #The 'error' material should probably be a more descriptive
    #name, like 'nonplanar error correction' or something
    try:
        e_mat = bpy.data.materials["error"]
    except:
        e_mat = bpy.data.materials.new(name= "error")
        
    e_mat.use_nodes = True

    bpy.context.object.active_material = e_mat

    p_node = e_mat.node_tree.nodes.get('Principled BSDF')
    p_node.inputs[0].default_value = [1,0,0,1]

    for face in faces:
        face.select_set(True)
        
    bpy.ops.object.material_slot_assign()

#Get the heck out of edit mode, which also has the added benefit 
#of updating and redrawing the object display

bpy.ops.object.mode_set(mode='OBJECT')

#If you go back into edit mode you'll note the corrected polys are 
#conveniently still selected, since they weren't explicitly deselected
#Though users might not want that and it's probably more polite
#to store and restore the original edit mode selection

```

**Comment by brunopostle** [comment]
Thanks! I committed a variation of the first version, it works fine because 'Homemaker Topologise' effectively discards the mesh when it creates the IFC model (it also uncovered another very basic bug #16).

But I will look again at the second version because the other function in the add-on (Topologise) needs to be fixed to copy the materials to the result, and for this it needs a clean materials list.

**Comment by elkmug** [comment]
_"(Topologise) needs to be fixed to copy the materials to the result, and for this it needs a clean materials list"._

Hmm, if that's the case maybe it would be better to use face maps to record the former non-planars rather than materials.

It doesn't give the user that immediate visual feedback, but on the plus side it does simplify the code a bit.  
( Don't confuse Face _maps_ with face _sets_.   Face sets would be great for this because they can be seen in the 3D view, but, unfortunately, they can only be seen in sculpt mode ¯\\\_(ツ)_/¯ )

```python
import bpy
import bmesh

ob = bpy.context.active_object
mesh = ob.data

f_maps = ob.face_maps

leng = len(f_maps)

ob_has_f_map = False

for i in range(leng):
    if f_maps[i].name == "nonplanar":
        ob_has_f_map = True
        break       

bpy.ops.object.mode_set(mode='EDIT')

md = bmesh.from_edit_mesh(mesh)

output = bmesh.ops.connect_verts_nonplanar(md,angle_limit = 0.001,faces = md.faces)

faces = output["faces"]

if len(faces) > 0:
    bpy.ops.mesh.select_all(action='DESELECT')
    
    if ob_has_f_map:
        f_maps.active_index = i
    else:
        f_maps.new(name="nonplanar")

    for face in faces:
        face.select_set(True)

    bpy.ops.object.face_map_assign()    

bpy.ops.object.mode_set(mode='OBJECT')
```

**Comment by brunopostle** [comment]
@elkmug I wonder if I should be using facemaps in the first place. I'm only using materials as a hacky way to tag faces with labels for processing as styles later.

This has already caused confusion: the user creates materials, which become architectural styles, which have altogether different materials.

**Comment by elkmug** [comment]
Implementation-wise Materials are pretty complex things. They're their own entity, can be linked to any number of objects or a 'fake user' or nothing all, and as you point out, can become really confusing, really fast.

Sadly the problem with Face maps is they're kind of an orphan thing, because they're part of a never fully implemented feature that's being abandoned in favor of a different feature which means they might get removed. 

I wasn't aware of that when I made the suggestion, sorry about that :{
 
I do think removal of Face maps would be shortsighted, because while they're similar to vertex groups, being poly based, rather than being point based, can be very useful. 

But, relying on them would be a gamble.
