### ISSUE TITLE
Walls are not displaying properly

### ISSUE THREAD

**Issue by wassimj** [brunopostle/homemaker-addon#41]
When I read back from the IFC file the ifcWall elements and display them, they do not look correct.
<img width="995" alt="f02" src="https://user-images.githubusercontent.com/6302909/155278033-e4ecf87a-5fcb-432b-acef-2742901d2d27.png">

**Comment by brunopostle** [comment]
Blender doesn't like faces with holes, so blenderbim triangulates everything in order to be able to display it in the viewport.

It looks like you are reading the raw face geometry - which is probably ultimately what you want in order to generate Topologic Faces (since an IFC face is a closer match to the Topologic face) - so you either need to find that blenderbim triangulate function, or figure out how to map from an IFC face with holes to a Topologic Face with holes.

**Comment by wassimj** [comment]
Hmm.. ifcopenshell gives opencascade BREPS. I convert that to Topologic objects directly. I do the triangulations when I display (in Topology.Geometry). I think there is something else going on here. 
I am using:
settings = ifcopenshell.geom.settings()
settings.set(settings.USE_BREP_DATA,True)
settings.set(settings.SEW_SHELLS,True)
settings.set(settings.USE_WORLD_COORDS,True)
ifc_file = ifcopenshell.open(filePath)
products = ifc_file.by_type("ifcWall")
topologies = []
for p in products:
   cr = ifcopenshell.geom.create_shape(settings, p)
   brepString = cr.geometry.brep_data
  topologies.append(topologic.Topology.ByString(brepString))

**Comment by brunopostle** [comment]
Sorry, no idea, I'm pretty clueless with this opencascade stuff

**Comment by brunopostle** [comment]
Resolved in IfcOpenShell/IfcOpenShell#2061
