### ISSUE TITLE
Sverchok Nodes - Errors

### ISSUE THREAD

**Issue by wassimj** [brunopostle/homemaker-addon#46]
I was able to integrate the new homemaker sverchok nodes into Topologic. I was also able to feed it a CellComplex from a Topologic node and create a BlenderBIM IFC. However, after changing width of building in the original CellComplex a couple of times, the IFCByCellComplex node puts up the following error:

`2022-05-16 09:15:17,161 [ERROR] blenderbim.bim.module.model.wall:972 : 'NoneType' object has no attribute 'verts'`
<img width="1920" alt="Homemaker-Error" src="https://user-images.githubusercontent.com/6302909/168549633-3a3cb08b-3431-4e46-8cae-3c3423c03b76.png">

**Comment by brunopostle** [comment]
Awesome, though I have no idea why this error happens.

The Homemaker node doesn't do any blenderbim stuff, i.e it is entirely topologic and ifcopenshell code, so I don't know how it is reporting a blenderbim error.

The other node doesn't do any Homemaker or topologic stuff. It is simply loads an IFC file in blenderbim (it doesn't need to have a 'Homemaker' name, since it should work to display your existing IFC related nodes' output).

There is definitely a bug with the second node, the old IFC data is not properly wiped when the new IFC is generated, but I didn't have time to investigate.

**Comment by brunopostle** [comment]
Maybe connect a stethoscope to the IFC output and disconnect the second node. This will show if the error is really in the first Homemaker node

**Comment by brunopostle** [comment]
Resolved
